name: Security Scan Pipeline

on:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    tags-ignore:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORG: johannshiryaev
  PROJECT_KEY: johannshiryaev_devsecops-pipeline

jobs:
  security-check:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - "3000:3000"

    steps:
      - name: "Checkout OWASP Juice Shop"
        uses: actions/checkout@v4
        with:
          repository: owasp-juice-shop/juice-shop
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create reports directory
        run: mkdir -p reports

      - name: "Run Gitleaks scan"
        run: |
          docker run --rm \
            -v $(pwd):/src \
            ghcr.io/gitleaks/gitleaks detect --source /src --no-git --report-format sarif \
            --report-path /src/reports/gitleaks-report.sarif --exit-code=0
  
      - name: Upload Gitleaks SARIF
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: reports/

      - name: Check for dependency files
        run: |
          find /src/frontend -type f -name "package.json"

      - name: "Build SBOM with Trivy"
        run: |
          docker run --rm \
            -v $(pwd):/src \
            ghcr.io/aquasecurity/trivy:latest \
            fs /src/frontend \
            --format cyclonedx \
            --output /src/reports/sbom.json

      - name: "Scan SBOM with Trivy"
        run: |
          docker run --rm \
            -v $(pwd):/src\
            ghcr.io/aquasecurity/trivy:latest \
            sbom /src/reports/sbom.json \
            -f sarif -o /src/reports/trivy-sbom.sarif

      - name: Upload Trivy SARIF
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom
          path: reports/

      - name: "Static analysis with SonarQube"
        run: |
          docker run --rm \
            -v $(pwd):/src \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=${{ env.PROJECT_KEY }} \
            -Dsonar.token=${{ env.SONAR_TOKEN }} \
            -Dsonar.organization=${{ env.SONAR_ORG }} \
            -Dsonar.sources=/src \
            -Dsonar.projectBaseDir=/src \
            -Dsonar.host.url=https://sonarcloud.io    

      - name: "Dynamic analysis with OWASP ZAP"
        run: |
          mkdir -p reports/zap
          docker run --rm \
            --network host \
            -v $(pwd)/reports/zap:/zap/wrk \
            -u root \
            zaproxy/zap-stable \
            zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html \
            -w zap-warnings.xml \
            -J zap-warnings.json \
            -I || true

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap/*

      - name: "Upload all reports"
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/